### ISSUE TITLE
AIO command for upgrade

### ISSUE THREAD

**Issue by maverick74** [fabiomux/zypper-upgraderepo#2]
This plugin is a great step in the right direction!!!

But i would like, if possible, to have an all-in-one command that would perform all the steps.

Something like a **zypper-upgraderepo --aiodup**, for example...

this would perform a system update, then check if new repos are available, upgrade them, and finally do a zypper dup over that new repos...

I don't know if this is even possible... but it would be a good start to have something like ubuntu has (we would still be missing a notification of new OS available... but it would be a start...)

**Comment by fabiomux** [comment]
Just published this script which drives through the whole upgrading process: https://github.com/fabiomux/zypper-upgradedistro

It's not totally automatic, it still asks for confirmations step by step, that because there are things that should be watched by the admin, and it runs from the command line.

For the notification, I should write something different that uses the taskbar maybe.
